# Use the 'paths-ignore' key to specify files and directories to exclude.
paths-ignore:
  # This pattern ignores all files ending in .jsonl within the 'data' folder
  # and any of its subdirectories.
  - "data/**/*.jsonl"